### ISSUE TITLE
ValueError: Unknown parameter arp for function〈fuctin _ at 0x000007438B9820) with type typing..Annotatedlarclet. alconna. arparma.Arparma，DependsInner(_alconna_matches，use_cache=False)]

### ISSUE THREAD

**Issue by xi-yue-233** [RF-Tar-Railt/nonebot-plugin-arkgacha#1]
![image](https://github.com/RF-Tar-Railt/nonebot-plugin-arkgacha/assets/58218656/b8d041e4-bfcf-46e1-a379-0bd44cb14c09)

**Comment by RF-Tar-Railt** [comment]
python版本?
nonebot2版本?

**Comment by xi-yue-233** [comment]
![image](https://github.com/RF-Tar-Railt/nonebot-plugin-arkgacha/assets/58218656/23f0c7ce-3c02-4a80-86f6-b1bbd298eaef)
![image](https://github.com/RF-Tar-Railt/nonebot-plugin-arkgacha/assets/58218656/0acf9fa8-56d7-4e08-ac97-ac6d2046e246)
nonebot2版本是2.0.0rc3
python版本是3.9.5

**Comment by RF-Tar-Railt** [comment]
> ![image](https://github.com/RF-Tar-Railt/nonebot-plugin-arkgacha/assets/58218656/23f0c7ce-3c02-4a80-86f6-b1bbd298eaef)
> 
> ![image](https://github.com/RF-Tar-Railt/nonebot-plugin-arkgacha/assets/58218656/0acf9fa8-56d7-4e08-ac97-ac6d2046e246)
> 
> nonebot2版本是2.0.0rc3
> 
> python版本是3.9.5

建议升级nb2为2.0.0rc4

其次，更新本插件，最新版本为0.1.3

**Comment by RF-Tar-Railt** [comment]
更正，更新0.1.4
帮助那里更新命令写错了

**Comment by xi-yue-233** [comment]
![image](https://github.com/RF-Tar-Railt/nonebot-plugin-arkgacha/assets/58218656/cf8e9377-759c-4a5a-aa5c-072cbd94ea75)
![image](https://github.com/RF-Tar-Railt/nonebot-plugin-arkgacha/assets/58218656/2214335b-2e63-4efb-aeef-3c6b82e4a63f)
又报新错误了

**Comment by RF-Tar-Railt** [comment]
> ![image](https://github.com/RF-Tar-Railt/nonebot-plugin-arkgacha/assets/58218656/cf8e9377-759c-4a5a-aa5c-072cbd94ea75)
> 
> ![image](https://github.com/RF-Tar-Railt/nonebot-plugin-arkgacha/assets/58218656/2214335b-2e63-4efb-aeef-3c6b82e4a63f)
> 
> 又报新错误了

看文档或者日志，要求使用“方舟十连”功能前运行命令“arkkit init”

**Comment by xi-yue-233** [comment]
执行过了，好像没反应
![image](https://github.com/RF-Tar-Railt/nonebot-plugin-arkgacha/assets/58218656/9b51fdf2-57b9-41f3-9fb9-67e4f846b1cc)

**Comment by xi-yue-233** [comment]
在控制台执行这个命令有反应了，不是对机器人发送的

**Comment by xi-yue-233** [comment]
应该可以用了
![image](https://github.com/RF-Tar-Railt/nonebot-plugin-arkgacha/assets/58218656/a8a3292e-8f25-44d0-9270-38428f436bfb)

**Comment by xi-yue-233** [comment]
建议增加抽卡cd的设置，现在群里被方舟抽卡刷屏了

**Comment by RF-Tar-Railt** [comment]
> 建议增加抽卡cd的设置，现在群里被方舟抽卡刷屏了

请开另一个issue
