### ISSUE TITLE
Bug: 出现异常

### ISSUE THREAD

**Issue by exusiai07** [RF-Tar-Railt/nonebot-plugin-arkgacha#10]
### 操作系统

Windows

### Python 版本

3.11.5

### NoneBot 版本

2.0.0

### 适配器

Onebot v11 2.2.2

### 描述问题

方舟抽卡命令无法运行，AlconnaMatcher定义的type为空字符串，导致无法使用getsize的attribute

### 复现步骤

1. 输入“方舟抽卡”或“方舟抽卡2”或方舟抽卡“200”均无法返回结果

### 截图或日志

<img width="872" alt="image" src="https://github.com/RF-Tar-Railt/nonebot-plugin-arkgacha/assets/112692808/c015699a-891d-4862-9bbd-04a846430d82">

**Comment by RF-Tar-Railt** [comment]
是PIL的问题

你pil版本多少，看降级能不能解决

**Comment by exusiai07** [comment]
> 是PIL的问题
> 
> 你pil版本多少，看降级能不能解决

谢谢大佬，这个问题今天再尝试的时候又不存在了
