### ISSUE TITLE
Bug: 使用ark init时出现异常

### ISSUE THREAD

**Issue by exusiai07** [RF-Tar-Railt/nonebot-plugin-arkgacha#11]
### 操作系统

Linux

### Python 版本

3.10.12

### NoneBot 版本

2.0.0

### 适配器

Onebot v11 2.2.2

### 描述问题

使用ark init以及运行插件时均出现以下报错
<img width="807" alt="image" src="https://github.com/RF-Tar-Railt/nonebot-plugin-arkgacha/assets/112692808/997accd3-7a57-4b16-96fe-d958ef20ee10">
<img width="750" alt="image" src="https://github.com/RF-Tar-Railt/nonebot-plugin-arkgacha/assets/112692808/03f93028-dfc5-4f32-9ae7-f19324019aee">

### 复现步骤

1. 使用nb-cli安装插件
2. 运行 nb arkgacha init
3. 出现以上报错

**Comment by RF-Tar-Railt** [comment]
更新后还有这问题吗
