### ISSUE TITLE
[Feature: 功能描述] 建议输出抽卡结果时回复发出指令者

### ISSUE THREAD

**Issue by QSlotus** [RF-Tar-Railt/nonebot-plugin-arkgacha#12]
### 希望能解决的问题

有的时候群友同时发`方舟十连`以至于结果混淆了
建议输出抽卡结果时回复发出指令者

### 描述所需要的功能

建议输出抽卡结果时回复发出指令者

**Comment by RF-Tar-Railt** [comment]
增加了配置项来选择这个功能
