### ISSUE TITLE
Bug: arkkit init时报错：AttributeError: 'EntryPoints' object has no attribute 'get'

### ISSUE THREAD

**Issue by LambdaYH** [RF-Tar-Railt/nonebot-plugin-arkgacha#15]
### 操作系统

Windows

### Python 版本

3.12.4

### NoneBot 版本

2.3.2

### 适配器

OnebotV11 2.4.4

### 描述问题

执行arkkit init时候报错

### 复现步骤

1. 执行arkkit init

### 截图或日志

```
arkkit init
```
```python
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\cheny\Documents\dev\pythonProject\MigangBot\.venv\Scripts\arkkit.EXE\__main__.py", line 7, in <module>
  File "C:\Users\cheny\Documents\dev\pythonProject\MigangBot\.venv\Lib\site-packages\arknights_toolkit\cli\__main__.py", line 4, in main
    arkkit.main()
  File "C:\Users\cheny\Documents\dev\pythonProject\MigangBot\.venv\Lib\site-packages\clilte\core.py", line 294, in main
    self.load_entry()
  File "C:\Users\cheny\Documents\dev\pythonProject\MigangBot\.venv\Lib\site-packages\clilte\core.py", line 223, in load_entry
    for entry in entry_points().get(f"litecli.{self.name}.plugins", []):
                 ^^^^^^^^^^^^^^^^^^
AttributeError: 'EntryPoints' object has no attribute 'get'
```

**Comment by RF-Tar-Railt** [comment]
你列出你bot环境里的包看看

**Comment by LambdaYH** [comment]
| 包| 版本 |
|:-----|:------|
| aiocache| 0.12.2| 
| aiofiles| 24.1.0| 
| aiohttp| 3.9.5| 
| aiosignal| 1.3.1| 
| aiosqlite| 0.17.0| 
| alembic| 1.13.2| 
| annotated-types| 0.7.0| 
| anyio| 3.7.1| 
| APScheduler| 3.10.4| 
| arclet-alconna| 1.8.19| 
| arclet-alconna-tools| 0.7.6| 
| arknights-toolkit| 0.7.4| 
| arrow| 1.3.0| 
| async-lru| 2.0.4| 
| asyncio-dgram| 2.1.2| 
| asyncpg| 0.29.0| 
| attrs| 23.2.0| 
| azure-cognitiveservices-speech| 1.38.0| 
| bbcode| 1.1.0| 
| beautifulsoup4| 4.12.3| 
| bidict| 0.23.1| 
| bilireq| 0.2.13| 
| binaryornot| 0.4.4| 
| black| 24.4.2| 
| Brotli| 1.1.0| 
| cachetools| 5.4.0| 
| cairocffi| 1.7.1| 
| CairoSVG| 2.7.1| 
| cashews| 7.1.0| 
| cattrs| 23.2.3| 
| certifi| 2024.7.4| 
| cffi| 1.16.0| 
| cfgv| 3.4.0| 
| chardet| 5.2.0| 
| charset-normalizer| 3.3.2| 
| cli-lite| 0.9.0| 
| click| 8.1.7| 
| cn2an| 0.5.22| 
| colorama| 0.4.6| 
| contourpy| 1.2.1| 
| cookiecutter| 2.6.0| 
| croniter| 1.4.1| 
| cssselect| 1.2.0| 
| cssselect2| 0.7.0| 
| cycler| 0.12.1| 
| dateparser| 1.2.0| 
| deep-translator| 1.11.4| 
| defusedxml| 0.7.1| 
| diro-py| 0.1.1| 
| distlib| 0.3.8| 
| distro| 1.9.0| 
| dnspython| 2.2.1| 
| email_validator| 2.2.0| 
| emoji| 2.12.1| 
| expiringdict| 1.2.2| 
| fake-useragent| 1.5.1| 
| fastapi| 0.111.1| 
| fastapi-cli| 0.0.4| 
| feedparser| 6.0.11| 
| filelock| 3.15.4| 
| filetype| 1.2.0| 
| fonttools| 4.53.1| 
| frozenlist| 1.4.1| 
| greenlet| 3.0.3| 
| grpcio| 1.65.1| 
| h11| 0.14.0| 
| httpcore| 1.0.5| 
| httptools| 0.6.1| 
| httpx| 0.27.0| 
| identify| 2.6.0| 
| idna| 3.7| 
| imageio| 2.34.2| 
| importlib_metadata| 8.2.0| 
| iso8601| 1.1.0| 
| isort| 5.13.2| 
| jieba| 0.42.1| 
| Jinja2| 3.1.4| 
| kiwisolver| 1.4.5| 
| Levenshtein| 0.25.1| 
| loguru| 0.7.2| 
| lxml| 5.2.2| 
| Mako| 1.3.5| 
| Markdown| 3.6| 
| markdown-it-py| 3.0.0| 
| MarkupSafe| 2.1.5| 
| matplotlib| 3.9.1| 
| mcstatus| 10.0.3| 
| mdurl| 0.1.2| 
| meme-generator| 0.0.20| 
| msgpack| 1.0.8| 
| multidict| 6.0.5| 
| mypy-extensions| 1.0.0| 
| nb-cli| 1.4.1| 
| nepattern| 0.7.6| 
| nodeenv| 1.9.1| 
| nonebot-adapter-onebot| 2.4.4| 
| nonebot-bison-migang| 0.1.6| 
| nonebot-plugin-alconna| 0.50.2| 
| nonebot-plugin-apscheduler| 0.5.0| 
| nonebot-plugin-arkgacha| 0.7.0| 
| nonebot-plugin-cesaa| 0.4.0| 
| nonebot-plugin-charpic-migang| 0.0.1| 
| nonebot-plugin-cocdicer| 0.4.0| 
| nonebot-plugin-datastore| 1.3.0| 
| nonebot-plugin-gachalogs| 0.2.13| 
| nonebot-plugin-gscode| 0.2.2| 
| nonebot-plugin-gsmaterial| 0.2.7| 
| nonebot-plugin-gspanel| 0.2.25| 
| nonebot-plugin-htmlrender| 0.3.3| 
| nonebot-plugin-localstore| 0.7.0| 
| nonebot-plugin-oddtext| 0.2.0| 
| nonebot-plugin-orm| 0.7.5| 
| nonebot-plugin-pingti| 0.1.4| 
| nonebot-plugin-send-anything-anywhere| 0.6.1| 
| nonebot-plugin-sentry| 2.0.0| 
| nonebot-plugin-waiter| 0.7.0| 
| nonebot-plugin-withdraw| 0.2.3| 
| nonebot-plugin-word-bank2| 0.1.8| 
| nonebot-plugin-wordcloud| 0.7.3| 
| nonebot2| 2.3.2| 
| nonebot_plugin_bottle| 2.0.1.1| 
| nonebot_plugin_chatrecorder| 0.6.0| 
| nonebot_plugin_ddcheck| 0.4.0| 
| nonebot_plugin_emojimix| 0.4.0| 
| nonebot_plugin_handle| 0.4.1| 
| nonebot_plugin_imagetools| 0.4.2| 
| nonebot_plugin_memes| 0.6.2| 
| nonebot_plugin_remake| 0.4.2| 
| nonebot_plugin_session| 0.3.1| 
| nonebot_plugin_session_orm| 0.2.0| 
| nonebot_plugin_shindan| 0.6.1| 
| nonebot_plugin_userinfo| 0.2.4| 
| nonebot_plugin_wordle| 0.4.1| 
| noneprompt| 0.1.9| 
| numpy| 1.26.4| 
| openai| 1.37.1| 
| opencv-python-headless| 4.10.0.84| 
| orjson| 3.10.6| 
| packaging| 24.1| 
| pathspec| 0.12.1| 
| PicImageSearch| 3.10.6| 
| pil-utils| 0.1.10| 
| pillow| 10.4.0| 
| platformdirs| 4.2.2| 
| playwright| 1.45.1| 
| pre-commit| 3.7.1| 
| proces| 0.1.7| 
| prompt_toolkit| 3.0.47| 
| protobuf| 5.27.2| 
| psutil| 5.9.8| 
| pycparser| 2.22| 
| pycryptodome| 3.20.0| 
| pydantic| 2.8.2| 
| pydantic_core| 2.20.1| 
| pyee| 11.1.0| 
| pyfiglet| 1.0.2| 
| pygal| 3.0.4| 
| Pygments| 2.18.0| 
| pygtrie| 2.5.0| 
| PyJWT| 2.8.0| 
| pymdown-extensions| 10.8.1| 
| pyparsing| 3.1.2| 
| pypika-tortoise| 0.1.6| 
| pypinyin| 0.51.0| 
| pypng| 0.20220715.0| 
| pyquery| 2.0.0| 
| pyspellchecker| 0.8.1| 
| python-dateutil| 2.9.0.post0| 
| python-dotenv| 1.0.1| 
| python-engineio| 4.9.1| 
| python-Levenshtein| 0.25.1| 
| python-markdown-math| 0.8| 
| python-multipart| 0.0.9| 
| python-slugify| 8.0.4| 
| python-socketio| 5.11.3| 
| pytz| 2024.1| 
| PyYAML| 6.0.1| 
| pyzbar| 0.1.9| 
| qrcode| 7.4.2| 
| rapidfuzz| 3.9.4| 
| rcnb| 1.0.3| 
| regex| 2024.7.24| 
| requests| 2.32.3| 
| rich| 13.7.1| 
| ruamel.yaml| 0.18.6| 
| ruamel.yaml.clib| 0.2.8| 
| sentry-sdk| 2.11.0| 
| setuptools| 71.1.0| 
| sgmllib3k| 1.0.0| 
| shellingham| 1.5.4| 
| shelved-cache| 0.3.1| 
| simple-websocket| 1.0.0| 
| six| 1.16.0| 
| sniffio| 1.3.1| 
| soupsieve| 2.5| 
| SQLAlchemy| 2.0.31| 
| starlette| 0.37.2| 
| StrEnum| 0.4.15| 
| tarina| 0.5.4| 
| tenacity| 8.5.0| 
| text-unidecode| 1.3| 
| thefuzz| 0.22.1| 
| tinycss2| 1.3.0| 
| tinydb| 4.8.0| 
| toml| 0.10.2| 
| tomlkit| 0.13.0| 
| tortoise-orm| 0.21.5| 
| tqdm| 4.66.4| 
| typer| 0.12.3| 
| types-python-dateutil| 2.9.0.20240316| 
| typing_extensions| 4.12.2| 
| tzdata| 2024.1| 
| tzlocal| 5.2| 
| ujson| 5.10.0| 
| urllib3| 2.2.2| 
| uvicorn| 0.30.3| 
| virtualenv| 20.26.3| 
| watchfiles| 0.22.0| 
| wcwidth| 0.2.13| 
| webencodings| 0.5.1| 
| websockets| 12.0| 
| win32-setctime| 1.1.0| 
| wordcloud| 1.9.3| 
| wsproto| 1.2.0| 
| XlsxWriter| 3.2.0| 
| yarl| 1.9.4| 
| YetAnotherPicSearch| 1.9.6| 
| zipp| 3.19.2| 


pyproject文件
```toml
dependencies = [
    "nonebot2[fastapi,httpx]>=2.1.3",
    "pydantic[dotenv]>=1.10.10",
    "nonebot-adapter-onebot<3.0.0,>=2.3.1",
    "nonebot-plugin-apscheduler<1.0.0,>=0.3.0",
    "ujson<6.0.0,>=5.8.0",
    "ruamel-yaml<1.0.0,>=0.17.32",
    "async-lru<3.0.0,>=2.0.2",
    "tortoise-orm[accel,asyncpg]<1.0.0,>=0.19.3",
    "aiohttp[speedups]<4.0.0,>=3.8.4",
    "lxml<5.0.0,>=4.9.2",
    "tenacity<9.0.0,>=8.2.1",
    "fake-useragent<2.0.0,>=1.1.1",
    "aiocache<1.0.0,>=0.12.1",
    "azure-cognitiveservices-speech<2.0.0,>=1.29.0",
    "deep-translator<2.0.0,>=1.11.4",
    "pyzbar<1.0.0,>=0.1.9",
    "anyio<4.0.0,>=3.7.0",
    "mcstatus<11.0.0,>=10.0.3",
    "croniter<2.0.0,>=1.4.1",
    "python-levenshtein<1.0.0,>=0.21.1",
    "thefuzz<1.0.0,>=0.19.0",
    "psutil<6.0.0,>=5.9.5",
    "cattrs<24.0.0,>=23.1.1",
    "pil-utils<1.0.0,>=0.1.7",
    "nb-cli<2.0.0,>=1.1.2",
    "cn2an<1.0.0,>=0.5.19",
    "pygal<4.0.0,>=3.0.0",
    "qrcode<8.0.0,>=7.4.2",
    "openai>=1.0.0",
    "cairosvg<3.0.0,>=2.7.0",
    "cachetools<6.0.0,>=5.3.0",
    "dateparser<2.0.0,>=1.1.7",
    "feedparser<7.0.0,>=6.0.10",
    "uvicorn[standard]>=0.23.2",
    "nonebot-plugin-orm>=0.7.1",
    "nonebot-plugin-alconna>=0.41.0",
]
requires-python = ">=3.10,<4.0"
readme = "README.md"
license = {text = "AGPL-3.0"}

[project.optional-dependencies]
plugins = [
    "nonebot-plugin-word-bank2>=0.1.8",
    "nonebot-plugin-htmlrender>=0.2.3",
    "nonebot-plugin-memes>=0.6.1",
    "nonebot-plugin-shindan>=0.5.1",
    "nonebot-plugin-remake>=0.3.3",
    "nonebot-plugin-emojimix>=0.3.1",
    "nonebot-plugin-wordcloud>=0.6.1",
    "nonebot-plugin-ddcheck>=0.3.1",
    "nonebot-plugin-handle>=0.3.6",
    "nonebot-plugin-imagetools>=0.3.0",
    "nonebot-plugin-cocdicer>=0.4.0",
    "nonebot-plugin-withdraw>=0.2.3",
    "nonebot-plugin-datastore>=1.0.0",
    "nonebot-plugin-oddtext>=0.2.0",
    "nonebot-plugin-gachalogs>=0.2.13",
    "nonebot-plugin-arkgacha>=0.5.0",
    "nonebot-plugin-gspanel>=0.2.25",
    "nonebot-plugin-gsmaterial>=0.2.7",
    "nonebot-plugin-gscode>=0.1.8",
    "nonebot-plugin-wordle>=0.3.4",
    "nonebot-plugin-sentry>=0.4.1",
    "nonebot-plugin-bottle>=1.0.1",
    "nonebot-bison-migang>=0.1.4",
    "YetAnotherPicSearch>=1.9.6",
    "nonebot-plugin-charpic-migang>=0.0.1",
    "nonebot-plugin-pingti>=0.1.3",
]


[tool.pdm.resolution.overrides]
nonebot-plugin-localstore = ">=0.5.0"
nonebot-plugin-send-anything-anywhere = ">=0.4.0"
nonebot2 = ">=2.1.3"
httpx = ">=0.26.0"
pillow = ">=10.1.0"
lxml = ">= 0.6.0"
nonebot-plugin-apscheduler = ">=0.4.0"

[tool.nonebot]
adapters = [
    { name = "OneBot V11", module_name = "nonebot.adapters.onebot.v11" }
]
plugins = [
    "nonebot_plugin_apscheduler",
    "nonebot_plugin_datastore",
    "nonebot_plugin_htmlrender",
    "nonebot_plugin_orm",
    "nonebot_plugin_alconna",
    "nonebot_plugin_sentry",
    "nonebot_plugin_memes",
    "nonebot_plugin_word_bank2",
    "nonebot_bison",
    "nonebot_plugin_shindan",
    "nonebot_plugin_remake",
    "nonebot_plugin_emojimix",
    "nonebot_plugin_wordcloud",
    "nonebot_plugin_ddcheck",
    "nonebot_plugin_handle",
    "nonebot_plugin_imagetools",
    "nonebot_plugin_cocdicer",
    "nonebot_plugin_withdraw",
    "nonebot_plugin_oddtext",
    "nonebot_plugin_gachalogs",
    "nonebot_plugin_gspanel",
    "nonebot_plugin_gsmaterial",
    "nonebot_plugin_gscode",
    "nonebot_plugin_wordle",
    "nonebot_plugin_bottle",
    "nonebot_plugin_arkgacha",
    "YetAnotherPicSearch",
    "nonebot_plugin_charpic",
    "nonebot_plugin_pingti"
]
plugin_dirs = ["migang/core/core_plugins", "migang/plugins"]

[tool.black]
line-length = 88
include = '\.pyi?$'
extend-exclude = '''
'''

[tool.isort]
profile = "black"
line_length = 88
length_sort = true
skip_gitignore = true
force_sort_within_sections = true
extra_standard_library = ["typing_extensions"]

[tool.pdm]

[tool.pdm.build]
includes = []

[tool.pdm.options]
update = ["--update-eager"]

[tool.pdm.scripts]
install = "pdm install --prod -G plugins"
update_db = "nb datastore upgrade"
start = "nb run"
all = {composite = ["update_db", "start"]}

[tool.pdm.dev-dependencies]
format = [
    "black>=23.3.0",
    "isort>=5.12.0",
]
git = [
    "pre-commit>=3.3.3",
]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

```

**Comment by RF-Tar-Railt** [comment]
~~更新 cli-lite 到 0.10.0~~
~~更新arknights-toolkit到0.7.5~~
更新插件到0.8.0
