### ISSUE TITLE
无法安装

### ISSUE THREAD

**Issue by 4goten** [RF-Tar-Railt/nonebot-plugin-arkgacha#6]
E:\nbsf\ww>nb plugin install nonebot-plugin-arkgacha
使用虚拟环境: E:\nbsf\ww\.venv\Scripts\python.exe
WARNING: Ignoring invalid distribution -illow (e:\nbsf\ww\.venv\lib\site-packages)
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
ERROR: Could not find a version that satisfies the requirement nonebot-plugin-arkgacha (from versions: none)
ERROR: No matching distribution found for nonebot-plugin-arkgacha

**Comment by RF-Tar-Railt** [comment]
> E:\nbsf\ww>nb plugin install nonebot-plugin-arkgacha
> 
> 使用虚拟环境: E:\nbsf\ww\.venv\Scripts\python.exe
> 
> WARNING: Ignoring invalid distribution -illow (e:\nbsf\ww\.venv\lib\site-packages)
> 
> Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
> 
> ERROR: Could not find a version that satisfies the requirement nonebot-plugin-arkgacha (from versions: none)
> 
> ERROR: No matching distribution found for nonebot-plugin-arkgacha

python版本？

**Comment by 4goten** [comment]
3.10

**Comment by RF-Tar-Railt** [comment]
新开一个issue，按刚更新的模版来
这个先关掉

**Comment by RF-Tar-Railt** [comment]
以及大概知道了，你用的清华源还没同步这个插件
你切回官方源再试试
