### ISSUE TITLE
Bug: 插件出现异常，导致Bot无法启动

### ISSUE THREAD

**Issue by PackageInstaller** [RF-Tar-Railt/nonebot-plugin-arkgacha#8]
### 操作系统

Linux

### Python 版本

3.11.3

### NoneBot 版本

2.0.0rc4

### 适配器

Oebot v11 （版本不清楚）

### 描述问题

FileNotFoundError: [Errno 2] No such file or directory: '/home/Neko/.cache/pypoetry/virtualenvs/zhenxun-bot-uIXH1-31-py3.11/lib/python3.11/site-packages/arknights_toolkit/resource/ops_initialized'

### 复现步骤

1.git clone https://github.com/RF-Tar-Railt/nonebot-plugin-arkgacha.git
2.pip install nonebot-plugin-arkgacha -U
3.启动Bot

### 期望的结果

希望能找到问题所在，多有劳烦，望见谅

### 截图或日志

![image](https://github.com/RF-Tar-Railt/nonebot-plugin-arkgacha/assets/80018096/b8b22cff-2a3d-4774-9b56-96712cd9edb0)
![image](https://github.com/RF-Tar-Railt/nonebot-plugin-arkgacha/assets/80018096/18eb00dc-489b-4d40-8782-c7859473a06e)

**Comment by RF-Tar-Railt** [comment]
进入虚拟环境后命令行内执行 `arkkit init`

**Comment by PackageInstaller** [comment]
好，资源下载中，下完了没问题我close issue

**Comment by RF-Tar-Railt** [comment]
记得阅读一遍README

**Comment by PackageInstaller** [comment]
> 记得阅读一遍README

因为我这个不是原版nonnebot,我以为那个命令行是nb专属的什么（
