### ISSUE TITLE
能不能加入自动初始化

### ISSUE THREAD

**Issue by aknyzsd** [RF-Tar-Railt/nonebot-plugin-arkgacha#9]
### 希望能解决的问题

看了文档了（萌新）在windows系统下面不会使用初始化，启动出现错误
用cmd说找不到arkkit 这个命令
使用python提示语法错误
应该用什么命令行来初始化呢

### 描述所需要的功能

希望加个自动初始化，对萌新非常友好qwq

**Comment by RF-Tar-Railt** [comment]
这个插件是有自动初始化功能的

你直接运行插件试试

**Comment by aknyzsd** [comment]
会出现报错
![image](https://github.com/RF-Tar-Railt/nonebot-plugin-arkgacha/assets/121467598/e999e2bd-4690-4f65-a7be-0cf283747399)

**Comment by aknyzsd** [comment]
在这之后就强制退出nb了

**Comment by RF-Tar-Railt** [comment]
> 会出现报错
> ![image](https://github.com/RF-Tar-Railt/nonebot-plugin-arkgacha/assets/121467598/e999e2bd-4690-4f65-a7be-0cf283747399)
> 

你插件版本是多少

**Comment by aknyzsd** [comment]
0.3.0

**Comment by RF-Tar-Railt** [comment]
> 0.3.0

更新一下上游依赖版本

pip install -U arknights_toolkit

**Comment by aknyzsd** [comment]
更新后运行可以进入nb，抽卡出现新的报错强制退出
![image](https://github.com/RF-Tar-Railt/nonebot-plugin-arkgacha/assets/121467598/f248de15-3029-4ab2-9954-f145e258cc38)

**Comment by RF-Tar-Railt** [comment]
> 更新后运行可以进入nb，抽卡出现新的报错强制退出
> ![image](https://github.com/RF-Tar-Railt/nonebot-plugin-arkgacha/assets/121467598/f248de15-3029-4ab2-9954-f145e258cc38)
> 

看来是没初始化完就有指令了（

关掉bot，在进入了虚拟环境的前提下运行 arkkit init

**Comment by RF-Tar-Railt** [comment]
看来我得给nbcli加个拓展指令（

**Comment by aknyzsd** [comment]
进入什么虚拟环境呢qwq？
这样嘛：python->arkkit init -SIMG

**Comment by RF-Tar-Railt** [comment]
> 进入什么虚拟环境呢qwq？
> 这样嘛：python->arkkit init -SIMG

emm
你的bot是怎么安装的

**Comment by aknyzsd** [comment]
nb plugin

**Comment by aknyzsd** [comment]
约等于pip install?

**Comment by RF-Tar-Railt** [comment]
> nb plugin 
> 

输入命令
`. ./.venv/Scripts/activate`

然后 arkkit init

**Comment by aknyzsd** [comment]
不太理解，我还是上截图吧qwq
![image](https://github.com/RF-Tar-Railt/nonebot-plugin-arkgacha/assets/121467598/0df05eb3-5953-4c7a-baf7-238ebf80ddb2)

**Comment by RF-Tar-Railt** [comment]
> 不太理解，我还是上截图吧qwq
> ![image](https://github.com/RF-Tar-Railt/nonebot-plugin-arkgacha/assets/121467598/0df05eb3-5953-4c7a-baf7-238ebf80ddb2)
> 

先关掉你的python

然后输入 `powershell` 命令

等powershell启动后再输入命令
`.  .\.venv\Scripts\activate`

**Comment by aknyzsd** [comment]
![image](https://github.com/RF-Tar-Railt/nonebot-plugin-arkgacha/assets/121467598/7f159ca5-30cc-4519-a3fd-1cf66f106b67)
阿巴阿巴阿巴阿巴

**Comment by RF-Tar-Railt** [comment]
> ![image](https://github.com/RF-Tar-Railt/nonebot-plugin-arkgacha/assets/121467598/7f159ca5-30cc-4519-a3fd-1cf66f106b67)
> 阿巴阿巴阿巴阿巴

你输入ls命令一下

**Comment by aknyzsd** [comment]
![image](https://github.com/RF-Tar-Railt/nonebot-plugin-arkgacha/assets/121467598/cdb403fb-2b65-4546-82b8-45fb15d17340)
这个嘛？

**Comment by RF-Tar-Railt** [comment]
> ![image](https://github.com/RF-Tar-Railt/nonebot-plugin-arkgacha/assets/121467598/cdb403fb-2b65-4546-82b8-45fb15d17340)
> 这个嘛？

在你的bot文件夹那输入这个命令

**Comment by aknyzsd** [comment]
![image](https://github.com/RF-Tar-Railt/nonebot-plugin-arkgacha/assets/121467598/c7775df0-e437-456f-ad9e-faba89f966d5)

**Comment by RF-Tar-Railt** [comment]
> ![image](https://user-images.githubusercontent.com/121467598/255583859-c7775df0-e437-456f-ad9e-faba89f966d5.png)

hm?
![image](https://github.com/RF-Tar-Railt/nonebot-plugin-arkgacha/assets/42648639/f3afef13-ee6a-44a5-900d-b138633cd1f5)
你发一下你用 nb run 运行bot的时候这里提示的什么

**Comment by aknyzsd** [comment]
大概是这样的，再往下就是加载yi一些不重要的插件了
![image](https://github.com/RF-Tar-Railt/nonebot-plugin-arkgacha/assets/121467598/0289749d-4b8b-47dd-b584-a8d36d699c7b)

**Comment by RF-Tar-Railt** [comment]
> 大概是这样的，再往下就是加载yi一些不重要的插件了
> ![image](https://github.com/RF-Tar-Railt/nonebot-plugin-arkgacha/assets/121467598/0289749d-4b8b-47dd-b584-a8d36d699c7b)
> 

看起来你这没有用到虚拟环境

试一试 pip show arknights_toolkit

**Comment by aknyzsd** [comment]
![image](https://github.com/RF-Tar-Railt/nonebot-plugin-arkgacha/assets/121467598/1e64997a-3dd3-42ba-a5e8-04e6dd2ff90c)

**Comment by aknyzsd** [comment]
启动bot后依然是上面的报错

**Comment by RF-Tar-Railt** [comment]
> ![image](https://github.com/RF-Tar-Railt/nonebot-plugin-arkgacha/assets/121467598/1e64997a-3dd3-42ba-a5e8-04e6dd2ff90c)
> 

那应该可以直接命令行输入
`arkkit init` 的

**Comment by aknyzsd** [comment]
问题找到了，我需要转到arkkit.exe的目录下才能使用，但是nbplugininstall这个命令并不会把他安装在bot目录下，所以不能使用，gan'x感谢！
![image](https://github.com/RF-Tar-Railt/nonebot-plugin-arkgacha/assets/121467598/44f75839-109b-4be4-83a1-161c93acc55a)

**Comment by RF-Tar-Railt** [comment]
刚更新的0.4.0版本插件为 nb-cli 增加了一个命令 `nb arkgacha` ,之后用这个会更方便了

**Comment by aknyzsd** [comment]
![image](https://github.com/RF-Tar-Railt/nonebot-plugin-arkgacha/assets/121467598/a2805423-af48-40e6-a42c-4b3bdbdf1a8b)
在使用nb arkgacha init 后出现一个错误

**Comment by RF-Tar-Railt** [comment]
> ![image](https://github.com/RF-Tar-Railt/nonebot-plugin-arkgacha/assets/121467598/a2805423-af48-40e6-a42c-4b3bdbdf1a8b)
> 在使用nb arkgacha init 后出现一个错误
> 

是bug，我修一下

**Comment by RF-Tar-Railt** [comment]
> ![image](https://github.com/RF-Tar-Railt/nonebot-plugin-arkgacha/assets/121467598/a2805423-af48-40e6-a42c-4b3bdbdf1a8b)
> 在使用nb arkgacha init 后出现一个错误
> 

0.4.1，试试

**Comment by aknyzsd** [comment]
彳亍，我康康去

**Comment by aknyzsd** [comment]
好了，没有问题了，咱是不是每天早上七点半左右有一个自动更新，我这每天早上定点退出

**Comment by aknyzsd** [comment]
初始化又出现了问题，这次使用了miniconda虚拟环境，![Screenshot_20240310_213050_com.wujie.connect.jpg](https://github.com/RF-Tar-Railt/nonebot-plugin-arkgacha/assets/121467598/7e97be8c-adb5-45ea-828f-a2213888b777)![Screenshot_20240310_214045.jpg](https://github.com/RF-Tar-Railt/nonebot-plugin-arkgacha/assets/121467598/0690c395-95bc-488d-8de2-8d4e6902d0e7)

**Comment by RF-Tar-Railt** [comment]
> 初始化又出现了问题，这次使用了miniconda虚拟环境，![Screenshot_20240310_213050_com.wujie.connect.jpg](https://private-user-images.githubusercontent.com/121467598/311513604-7e97be8c-adb5-45ea-828f-a2213888b777.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwNzg3NTgsIm5iZiI6MTcxMDA3ODQ1OCwicGF0aCI6Ii8xMjE0Njc1OTgvMzExNTEzNjA0LTdlOTdiZThjLWFkYjUtNDVlYS04MjhmLWEyMjEzODg4Yjc3Ny5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMFQxMzQ3MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YmYyMGYxYjhiZjVhOTFhMTA4NDdlN2Q0NmY3YWZkZjdkMTk1MTk5ODY5ZTZlYjI0Mzg4OTA0YWZjN2NhZDdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.upnDG_P7Crr5TnImjwyudhIVcGxV0DVqyb25HnP7Nqc)![Screenshot_20240310_214045.jpg](https://private-user-images.githubusercontent.com/121467598/311514084-0690c395-95bc-488d-8de2-8d4e6902d0e7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwNzg3NTgsIm5iZiI6MTcxMDA3ODQ1OCwicGF0aCI6Ii8xMjE0Njc1OTgvMzExNTE0MDg0LTA2OTBjMzk1LTk1YmMtNDg4ZC04ZGUyLThkNGU2OTAyZDBlNy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMFQxMzQ3MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOWQzZTdkNTQwMTk2ZDg2NmFlNGRlNGFlNDVhN2M2MGQxNWE5NDBlZWU1Yzk0MDVlZDhiNjBmZTcxOWNhZGNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hGck0CSM_YEre2B56QjhhatUxPS6xhHI9V6_DXCAprE)

更新 nonebot-plugin-alconna 到0.40.0rc3

**Comment by aknyzsd** [comment]
更新后问题依旧，不过由于pip源没有更新所以下载的zip进行替换的，不知有没有影响

**Comment by RF-Tar-Railt** [comment]
> 更新后问题依旧，不过由于pip源没有更新所以下载的zip进行替换的，不知有没有影响

你自己pip show nonebot-plugin-alconna 看一下啊

**Comment by RF-Tar-Railt** [comment]
![image](https://github.com/RF-Tar-Railt/nonebot-plugin-arkgacha/assets/42648639/1d7330ea-278b-4f02-a76e-eaf9d7a3928f)

**Comment by aknyzsd** [comment]
修正一下，在cmd界面使用arkkit init -SIMG会出现init参数错误但是进bot后会自动初始化，刚才在配置其他的环境没有注意到，抱歉(-人-)

**Comment by RF-Tar-Railt** [comment]
> 修正一下，在cmd界面使用arkkit init -SIMG会出现init参数错误但是进bot后会自动初始化，刚才在配置其他的环境没有注意到，抱歉(-人-)

![image](https://github.com/RF-Tar-Railt/nonebot-plugin-arkgacha/assets/42648639/8e8f6a1d-5544-4677-856b-fca103752d80)
我这同样也没有出现问题

更新：我先发了个0.6.0，你更新看看先

**Comment by aknyzsd** [comment]
奇怪，这条命令是可以在bot根目录下使用的吧？![Screenshot_20240310_231416_com.wujie.connect.jpg](https://github.com/RF-Tar-Railt/nonebot-plugin-arkgacha/assets/121467598/f6002b2c-f10e-4051-9c41-72c4093b46fa)

**Comment by RF-Tar-Railt** [comment]
> 奇怪，这条命令是可以在bot根目录下使用的吧？![Screenshot_20240310_231416_com.wujie.connect.jpg](https://private-user-images.githubusercontent.com/121467598/311520326-f6002b2c-f10e-4051-9c41-72c4093b46fa.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwODQwNzIsIm5iZiI6MTcxMDA4Mzc3MiwicGF0aCI6Ii8xMjE0Njc1OTgvMzExNTIwMzI2LWY2MDAyYjJjLWYxMGUtNDA1MS05YzQxLTcyYzQwOTNiNDZmYS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMFQxNTE2MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZDI4NmJiN2U2YjkxY2Y3MWVhOWIwMDE3NDgxYzZjYWUxM2ViZGRiMzRkZTZjNjRmZjQ3ZDVmNGNiMGY3YmYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dXEElTxx6uBM600IpTlPZfR2fm5KfGdq_Gd_b8lV4xQ)

pip show arknights-toolkit
pip show arclet-alconna
arkkit --help
都看一下

**Comment by aknyzsd** [comment]
![Screenshot_20240310_232349_com.wujie.connect.jpg](https://github.com/RF-Tar-Railt/nonebot-plugin-arkgacha/assets/121467598/5b96f32e-6a6f-46c2-99d3-f8343cc47411)

**Comment by RF-Tar-Railt** [comment]
> ![Screenshot_20240310_232349_com.wujie.connect.jpg](https://private-user-images.githubusercontent.com/121467598/311520955-5b96f32e-6a6f-46c2-99d3-f8343cc47411.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwODQ2NDAsIm5iZiI6MTcxMDA4NDM0MCwicGF0aCI6Ii8xMjE0Njc1OTgvMzExNTIwOTU1LTViOTZmMzJlLTZhNmYtNDZjMi05OWQzLWY4MzQzY2M0NzQxMS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMFQxNTI1NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNGRmZjE3MGZiNjFlOTg1NzEyM2RiYTAyNzZiMzc5NWEzZDcxMjVkNzM4ODJiZTA3OGQ3MTI0ZTk0Y2Q3ODIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XkvMrVgGQrD6ER147ZsvAVof06Vk3D_TDkZ8c8v_CUk)

更新 arclet-alconna 到1.8.5
